spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  hikari:
    maximum-pool-size: 10
    max-lifetime: 840000   # 14 минут (немного меньше 15)
    idle-timeout: 300000   # 5 минут
    keepalive-time: 240000 # 4 минуты

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    cron: ${BOT_CRON:0 30 11,18 * * *}
